### PR TITLE
Terraform v.013 upgrade; PR template; and GH Actions integration

### PR DESCRIPTION
**Pull request by vab**
Developer Checklist

[X ] The README contains the correct list of dependencies, inputs, and outputs (e.g., terraform-docs markdown . has been run)
[N/A] Latest versions of stage.tfvars and prod.tfvars uploaded to mit-tfvars S3 bucket
[N/A] Stakeholder approval has been confirmed (or is not needed)
[N/A] Resources currently deploy to stage workspace
A terraform plan should show Plan: 2 to add, 0 to change, 0 to destroy.

What does this PR do?
This PR updates the Terraform code for tf-mod-alb to Terraform v0.13.

Helpful background context
The specific changes to this code include updating the required Terraform version in versions.tf to 0.13, the MIT Libraries GH actions code was integrated, the MIT Libraries PR template was integrated, and finally some minor code clean up (reorder vars to match the README.md file and remove extra whitespace) was done.

I also upgraded the Terraform version in the network build yml files. This may cause build failures until all of the network code is upgraded to v0.13.7. However, doing that upgrade now makes this PR a clean v0.13.7 upgrade. We will not have to come back and make a new PR after the network code upgrade is complete.

Requires Database Migrations?
NO

Includes new or updated dependencies?
NO

### CODE REVIEW

**Comment by zotoMIT** [comment]
Hey Alex, 
This should probably have just a validate action, doing the network actions is overkill here and we would need to make a lot of changes to make them work anyway.  
The versions block should include the required provider, AWS.

**Comment by vab** [comment]
@zotoMIT I've made the changes that you suggested.

**Review by zotoMIT — APPROVED** [review]
Looks good to me!

**Review by tim-rix — APPROVED** [review]
Looks goo to me.

**Pull request merged**
